{"ray": {"sid": "b50856f20ed7400eb0503ad48d2e2c46", "uid": null, "qid": "5c0a2363077c44eeae68170f218d3706", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [5c0a2363077c44eeae68170f218d3706]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 127, in execute\n    agent_executor = get_model_state()\n                     ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 75, in get_model_state\n    tools=render_text_description(tools),\n                                  ^^^^^\nUnboundLocalError: cannot access local variable 'tools' where it is not associated with a value\n", "created_at": "2023-12-30T12:46:02.451087"}], "status": "FAILED", "created_at": "2023-12-30T12:46:00.225915", "updated_at": "2023-12-30T12:46:02.458165", "finished": true}, "in": {"text": ["string"]}, "out": {}}